/**
 * System-wide RBAC Constants & Definitions
 * Defines the 5 canonical roles and granular permissions across all 9 modules.
 */

const ROLES = {
  ADMIN: 'admin',
  HR_PAYROLL_MANAGER: 'hr_payroll_manager',
  HR_PAYROLL_USER: 'hr_payroll_user',
  HR_MANAGER: 'hr_manager',
  EMPLOYEE: 'employee',
};

const MODULES = {
  EMPLOYEE: 'employee',
  ATTENDANCE: 'attendance',
  LEAVE: 'leave',
  CONTRACT: 'contract',
  PAYROLL: 'payroll',
  PAYSLIP: 'payslip',
  SALARY_STRUCTURE: 'salary_structure',
  SALARY_RULE: 'salary_rule',
  ADMIN: 'admin',
};

const PERMISSIONS = {
  // Employee
  EMPLOYEE_READ: 'employee:read',
  EMPLOYEE_READ_OWN: 'employee:read_own',
  EMPLOYEE_CREATE: 'employee:create',
  EMPLOYEE_UPDATE: 'employee:update',
  EMPLOYEE_DELETE: 'employee:delete',

  // Attendance
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_READ_OWN: 'attendance:read_own',
  ATTENDANCE_CREATE: 'attendance:create',
  ATTENDANCE_UPDATE: 'attendance:update',
  ATTENDANCE_DELETE: 'attendance:delete',
  ATTENDANCE_APPROVE: 'attendance:approve',

  // Leave
  LEAVE_READ: 'leave:read',
  LEAVE_READ_OWN: 'leave:read_own',
  LEAVE_CREATE: 'leave:create',
  LEAVE_UPDATE: 'leave:update',
  LEAVE_DELETE: 'leave:delete',
  LEAVE_APPROVE: 'leave:approve',

  // Contract
  CONTRACT_READ: 'contract:read',
  CONTRACT_READ_OWN: 'contract:read_own',
  CONTRACT_CREATE: 'contract:create',
  CONTRACT_UPDATE: 'contract:update',
  CONTRACT_DELETE: 'contract:delete',

  // Payroll
  PAYROLL_READ: 'payroll:read',
  PAYROLL_PROCESS: 'payroll:process',
  PAYROLL_APPROVE: 'payroll:approve',
  PAYROLL_LOCK: 'payroll:lock',
  PAYROLL_EXPORT: 'payroll:export',

  // Payslip
  PAYSLIP_READ_OWN: 'payslip:read_own',
  PAYSLIP_READ_ALL: 'payslip:read_all',
  PAYSLIP_GENERATE: 'payslip:generate',
  PAYSLIP_DOWNLOAD: 'payslip:download',

  // Salary Structure
  SALARY_STRUCTURE_READ: 'salary_structure:read',
  SALARY_STRUCTURE_MANAGE: 'salary_structure:manage',

  // Salary Rule
  SALARY_RULE_READ: 'salary_rule:read',
  SALARY_RULE_MANAGE: 'salary_rule:manage',

  // Admin
  ADMIN_ALL: 'admin:all',
  ADMIN_USERS_MANAGE: 'admin:users:manage',
  ADMIN_ROLES_MANAGE: 'admin:roles:manage',
  ADMIN_SETTINGS_MANAGE: 'admin:settings:manage',
};

// Default mapping of permissions per role
const ROLE_PERMISSIONS_MAP = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.HR_PAYROLL_MANAGER]: [
    // Employee
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_READ_OWN,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    // Attendance
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.ATTENDANCE_APPROVE,
    // Leave
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_UPDATE,
    PERMISSIONS.LEAVE_DELETE,
    PERMISSIONS.LEAVE_APPROVE,
    // Contract
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_READ_OWN,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_DELETE,
    // Payroll
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_EXPORT,
    // Payslip
    PERMISSIONS.PAYSLIP_READ_OWN,
    PERMISSIONS.PAYSLIP_READ_ALL,
    PERMISSIONS.PAYSLIP_GENERATE,
    PERMISSIONS.PAYSLIP_DOWNLOAD,
    // Salary Structure
    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_STRUCTURE_MANAGE,
    // Salary Rule
    PERMISSIONS.SALARY_RULE_READ,
    PERMISSIONS.SALARY_RULE_MANAGE,
  ],

  [ROLES.HR_PAYROLL_USER]: [
    // Payroll operations
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_EXPORT,
    // Payslip
    PERMISSIONS.PAYSLIP_READ_OWN,
    PERMISSIONS.PAYSLIP_READ_ALL,
    PERMISSIONS.PAYSLIP_GENERATE,
    PERMISSIONS.PAYSLIP_DOWNLOAD,
    // Read-only HR & Salary info for payroll computations
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_READ_OWN,
    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_RULE_READ,
  ],

  [ROLES.HR_MANAGER]: [
    // Full HR
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_READ_OWN,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_UPDATE,
    PERMISSIONS.LEAVE_DELETE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_READ_OWN,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_DELETE,
    PERMISSIONS.PAYSLIP_READ_OWN,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.EMPLOYEE_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.CONTRACT_READ_OWN,
    PERMISSIONS.PAYSLIP_READ_OWN,
  ],
};

module.exports = {
  ROLES,
  MODULES,
  PERMISSIONS,
  ROLE_PERMISSIONS_MAP,
};
